# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{loginza}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Galeta"]
  s.date = %q{2011-03-18}
  s.description = %q{Loginza - an interactive JavaScript widget provides visitors to your sites, a wide range of options for authentication through the accounts of common WEB-portals and services}
  s.email = %q{galeta.igor@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/loginza.rb",
    "lib/loginza/api.rb",
    "lib/loginza/railtie.rb",
    "lib/loginza/utils.rb",
    "lib/loginza/version.rb",
    "lib/loginza/view_helper.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{http://loginza.ru/}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{loginza}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails plugin for openID authentication by service Loginza.API}
  s.test_files = [
    "test/loginza_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end

